
name: mirror

on: [push, pull_request]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/init-ssh-action@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: cc332030/git-mirror-action@main
        timeout-minutes: 2
