
name: mirror

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/git-mirror-action@1.0.0
        timeout-minutes: 2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:${{ github.repository }}.git
          destination-repo: git@gitee.com:${{ github.actor }}/${{ github.event.repository.name }}.git
